blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/MasterJJJJ/package-for-group-project-for-dsci310/discussions
    about: Please ask and answer questions here.
